version: '3'
services:
  app:
    build: .
    environment:
      FLASK_ENV: stage
      PORT: 8080
      MCAM_MONGO_URI: mongodb://mcam:mcam@db:27017/admin
      MCAM_REDIS_URL: redis://redis:6379/0
    ports:
      - "8080:8080"
    links:
      - db
      - redis
  rq:
    build: .
    environment:
      FLASK_ENV: stage
      PORT: 8080
      MCAM_MONGO_URI: mongodb://mcam:mcam@db:27017/admin
      MCAM_REDIS_URL: redis://redis:6379/0
    links:
      - db
      - redis
    command:
      - supervisord
  redis:
    image: "redis:alpine"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mcam
      MONGO_INITDB_ROOT_PASSWORD: mcam
